module.exports = {
  docs: [
    {
      type: "category",
      label: "Developer Guidelines",
      items: [
        "open-source-guidelines",
        "engineering-culture",
        "agile-methodologies",
        "flight-methodology",
        "pair-mob-programming",
        "developer-tools",
        "developer-tools-ux-ui",
        "open-source-projects",
        "boilerplate",
        "material-ui",
        "visual-resources",
        "social-media-guidelines",
        "devops",
        "interplanetary-file-system",
        "blockchain-consensus-mechanism",
      ],
    },
    {
      type: "category",
      label: "Blockchain and Web3",
      link: {
        type: "doc",
        id: "blockchain-web3/blockchain-web3-index"
      },
      items: [
        "blockchain-web3/blockchain-web3-bitcoin",
        "blockchain-web3/blockchain-web3-ethereum",
        "blockchain-web3/blockchain-web3-base",
        "blockchain-web3/blockchain-web3-bsc",
        "blockchain-web3/blockchain-web3-polygon",
        "blockchain-web3/blockchain-web3-lightning",
        "blockchain-web3/blockchain-web3-nimiq",
        "blockchain-web3/blockchain-web3-nostr",
        "blockchain-web3/blockchain-web3-libre",
        "blockchain-web3/blockchain-web3-metamask",
        "blockchain-web3/blockchain-web3-rwa.io",
        "blockchain-web3/eos-learn/eosio-protocol",
        "blockchain-web3/eos-learn/consensus-mechanism",
        "blockchain-web3/eos-learn/system-resources",
        "blockchain-web3/eos-learn/eosio-components",
        "blockchain-web3/eos-learn/accounts-and-permissions",
        "blockchain-web3/eos-learn/important-functions",
        "blockchain-web3/eos-learn/private-keys",
        "blockchain-web3/eos-learn/dapp-development",
        "blockchain-web3/eos-learn/demux-pattern",
        "blockchain-web3/eos-learn/eos-blockchain",
        "blockchain-web3/eos-learn/smart-contract",
        "blockchain-web3/eos-learn/ricardian-contracts",
        "blockchain-web3/eos-learn/blockchain-security",
        "blockchain-web3/eos-learn/nfts-on-eosio",
        "blockchain-web3/eos-learn/migration-to-mandel",
        "blockchain-web3/eos-learn/eos-network-foundation"
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [
        "tutorials/markdown-guide",
        "tutorials/git-workflow-tutorial",
        "tutorials/github-guide",
        "tutorials/github-keys",
        "tutorials/react-tutorial",
        "tutorials/graphql-tutorial",
        "tutorials/docker",
        "tutorials/kubernetes",
        "tutorials/node-installation",
        "tutorials/private-network-installation",
        "tutorials/hello-world-contract",
        "tutorials/how-to-publish-packages",
        "tutorials/modern-cpp",
        "tutorials/how-to-mint",
      ],
    },
    {
      type: "category",
      label: "Tools",
      items: [
        "tools/glossary",
        "tools/command-line",
        "tools/nodeos-command-line-reference",
        "tools/sample-nodeos-configs",
        "tools/block-explorers",
        "tools/eosio-sdk-libraries",
        "tools/readme-file-template",
        "tools/example-eosio-smart-contract",
        "tools/frequently-asked-questions",
      ],
    },
    {
      type: "category",
      label: "Community Resources",
      items: [
        "community-resources/eosio-networks",
        "community-resources/telegram-channels",
        "community-resources/blog-posts",
        "community-resources/edenia-podcasts",
        "community-resources/useful-links",
      ],
    },
  ],
};
